### ISSUE TITLE
r2rml error

### ISSUE THREAD

**Issue by ngcps999** [ontop/ontop-api-examples#2]
Exception in thread "main" org.semanticweb.owlapi.reasoner.IllegalConfigurationException: it.unibz.inf.ontop.exception.InvalidMappingSourceQueriesException: The placeholder(s) wr_code in the target do(es) not occur in source query of the mapping assertion
[id: mapping--871660885
target atom: triple(s,p,o) with s/RDF(http://meraka/moss/exampleBooks.owl#author/{}/(TmpToTEXT(wr_code)),IRI), p/<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>, o/<http://meraka/moss/exampleBooks.owl#Author>
source query: select "wr_code", "wr_name" from "tb_affiliated_writers"]
	at it.unibz.inf.ontop.owlapi.impl.QuestOWL.<init>(QuestOWL.java:139)
	at it.unibz.inf.ontop.owlapi.impl.QuestOWLFactory.createReasoner(QuestOWLFactory.java:80)
	at it.unibz.inf.ontop.owlapi.impl.QuestOWLFactory.createReasoner(QuestOWLFactory.java:93)
	at it.unibz.inf.ontop.examples.owlapi.OntopOWLReasonerR2RMLMappingExample.run(OntopOWLReasonerR2RMLMappingExample.java:73)
	at it.unibz.inf.ontop.examples.owlapi.OntopOWLReasonerR2RMLMappingExample.main(OntopOWLReasonerR2RMLMappingExample.java:59)
Caused by: it.unibz.inf.ontop.exception.InvalidMappingSourceQueriesException: The placeholder(s) wr_code in the target do(es) not occur in source query of the mapping assertion
[id: mapping--871660885
target atom: triple(s,p,o) with s/RDF(http://meraka/moss/exampleBooks.owl#author/{}/(TmpToTEXT(wr_code)),IRI), p/<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>, o/<http://meraka/moss/exampleBooks.owl#Author>
source query: select "wr_code", "wr_name" from "tb_affiliated_writers"]
	at it.unibz.inf.ontop.spec.mapping.pp.impl.SQLPPMappingConverterImpl.convert(SQLPPMappingConverterImpl.java:120)
	at it.unibz.inf.ontop.spec.mapping.pp.impl.SQLPPMappingConverterImpl.convert(SQLPPMappingConverterImpl.java:83)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convert(SQLMappingExtractor.java:185)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.convertPPMapping(SQLMappingExtractor.java:146)
	at it.unibz.inf.ontop.spec.mapping.impl.SQLMappingExtractor.extract(SQLMappingExtractor.java:102)
	at it.unibz.inf.ontop.spec.impl.DefaultOBDASpecificationExtractor.extract(DefaultOBDASpecificationExtractor.java:40)
	at it.unibz.inf.ontop.injection.impl.OntopMappingConfigurationImpl.loadSpecification(OntopMappingConfigurationImpl.java:127)
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLConfigurationImpl.loadSpecification(OntopMappingSQLConfigurationImpl.java:84)
	at it.unibz.inf.ontop.injection.impl.OntopMappingSQLAllConfigurationImpl.loadSpecification(OntopMappingSQLAllConfigurationImpl.java:47)
	at it.unibz.inf.ontop.injection.impl.OntopSQLOWLAPIConfigurationImpl.loadOBDASpecification(OntopSQLOWLAPIConfigurationImpl.java:34)
	at it.unibz.inf.ontop.injection.impl.OntopOBDAConfigurationImpl.loadSpecification(OntopOBDAConfigurationImpl.java:44)
	at it.unibz.inf.ontop.injection.OntopSystemConfiguration.loadQueryEngine(OntopSystemConfiguration.java:20)
	at it.unibz.inf.ontop.owlapi.impl.QuestOWL.<init>(QuestOWL.java:134)
	... 4 more

**Comment by ghxiao** [comment]
Hi, the issue was because the example R2RML file is not correct anymore. In the latest version Ontop v4, we become more compliant with the R2RML standard, but also more restrictive about the casing in column names. In this example, we need to correct the mapping by explicitly quoting the columns. 

We have to fix the obda-to-r2rml conversion script as well. A separate issue will be created on the ontop repository.
